# Generated by Django 4.1.9 on 2023-06-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('registro', models.CharField(blank=True, max_length=25, null=True)),
                ('nome', models.CharField(max_length=150)),
                ('departamento', models.CharField(max_length=30)),
                ('funcao', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
