# Generated by Django 4.1.9 on 2023-06-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.BigAutoField(primary_key=True, serialize=False)),
                ('Register', models.IntegerField(blank=True, null=True)),
                ('EmployeeName', models.CharField(max_length=500)),
                ('Department', models.CharField(choices=[('Fiscal', 'Fiscal'), ('RH', 'RH'), ('TI', 'TI'), ('Vendas', 'Vendas'), ('Financeiro', 'Financeiro'), ('Produção', 'Produção'), ('Marketing', 'Marketing'), ('Logística', 'Logística')], max_length=30)),
                ('Role', models.CharField(choices=[('Gerente', 'Gerente'), ('Analista', 'Analista'), ('Desenvolvedor', 'Desenvolvedor'), ('Coordenador', 'Coordenador'), ('Assistente', 'Assistente'), ('Estagiário', 'Estagiário')], max_length=30)),
                ('DateOfJoining', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
    ]
